[tool.poetry]
name = "textstat"
version = "1.0.0-alpha.0"
description = "Textstat is an easy to use library to calculate statistics from text. It helps determine readability, complexity, and grade level."
authors = ["Alex Ward <alxwrd@googlemail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://textstat.github.io/"
repository = "https://github.com/textstat/textstat"
documentation = "https://textstat.github.io/docs"

[tool.poetry.scripts]
textstat = 'textstat.cli:run'


[tool.poetry.dependencies]
python = "^3.7"
pyphen = "^0.11.0"
textstat-en = {version = "1.0.0-alpha.0"}
typing-extensions = "^4.1.1"

[tool.poetry.dev-dependencies]
textstat-en = {path = "textstat-en", develop = true}
flake8 = "^4.0.1"
pytest = "^7.1.0"
grip = "^4.6.0"
poethepoet = "^0.13.1"
toml = "^0.10.2"
pytest-cov = "^3.0.0"
mypy = "^0.941"
black = "^22.1.0"
isort = "^5.10.1"

[tool.poetry.extras]
en = ["textstat-en"]

[tool.poe.tasks]
test = "pytest --cov=. --cov-report html:tests/coverage_report"
lint = "flake8 --exclude=build/,.venv/ --max-line-length=88 --per-file-ignores='__init__.py:F401'"
stubs = "stubgen -o textstat/stubs textstat-*"
check.sequence = ["lint", "test"]
check.ignore_fail = "return_non_zero"
black = "black ."
isort = "isort . --extend-skip=textstat/stubs"
format = ["black", "isort"]
build = "poetry build"
_publish = "poetry publish"
release = ["build", "_publish"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.coverage.run]
omit = [
    "tests/*",
    ".venv/*",
]